### ISSUE TITLE
TODO comments

### ISSUE THREAD

**Issue by kevinpaul468** [MihirRajeshPanchal/commentcleaner#11]
removing comments is a good thing, it makes the code much clean but it would be nice if TODO comments did not get deleted 
so that we know that we have some work to do on it

**Comment by kevinpaul468** [comment]
idk much about js but 
i see a lot of regular expressions in the code
i think if we implement the logic in re
for example in java
```
java: /\/\/.*|\/\*[\s\S]*?\*\/(?!.*TODO)/g
```
then it work i guess

**Comment by MihirRajeshPanchal** [comment]
Ok but not every developer using vscode will mark his comment as TODO?

**Comment by MihirRajeshPanchal** [comment]
we might have to add configurations to the vscode extension if you can solve this issue raise a pr @kevinpaul468

**Comment by MihirRajeshPanchal** [comment]
Sure you can work on this issue and raise a pr!

**Comment by LyubomirT** [comment]
> Sure you can work on this issue and raise a pr!

Alright, getting started on that right away.
