### ISSUE TITLE
strings with comment symbols are treated as comments

### ISSUE THREAD

**Issue by kevinpaul468** [MihirRajeshPanchal/commentcleaner#12]
![image](https://github.com/MihirRajeshPanchal/commentcleaner/assets/121682091/d9f07042-142a-46af-9c1a-bc01e84dab63)
![image](https://github.com/MihirRajeshPanchal/commentcleaner/assets/121682091/965c20e5-a075-40bc-931a-39e46da52ea2)

as you can see the string in print statement is being treated as a comment
this coud be a issue while using regualr expressions in program

**Comment by MihirRajeshPanchal** [comment]
Ok Nice Work If you can fix this raise a pr
